language: node_js
node_js:
  - "node"
  - "8"
  - "10"
# greenkeeper needs some extra attention package-lock files
# see: https://github.com/greenkeeperio/greenkeeper-lockfile
before_install:
  - npm install -g greenkeeper-lockfile@1
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
# by default Travis will run npm test
