name: Update License Year

on:
  schedule:
    - cron: '5 12 1 1 *'

jobs:
  update_license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update license year
        run: .github/workflows/update_license.sh